#include <iostream>
#include <string>
#include <stdlib.h>
#include <cstring>
using namespace std;


void calc (char a[],char b[],int m,int n) {

    int h[m];
    cout<<"Pattern sequence:"<<a<<endl<<"Text sequence:"<<b<<endl;

//h[]求める
    int i=0,j=1;
    h[1]=0;
    while(j<m) {
        while(i>0&&a[i]!=a[j]) i=h[i];
                    i++;j++;
        if(a[i]==a[j]) h[j]=h[i];
    else h[j]=i;

    }
    i=1;
    cout<<"h[i] ";
    while(i<=m){
cout<<h[i]<<",";
        i++;}

    cout<<endl;
//KMPアルゴリズム
int k=0;
  i=1; j=1;
    while(i<=m&&j<=n){
        while (i>0&&a[i]!=b[j]) i=h[i];
        i++;j++;
if(i>m) {cout <<"matched."<<i<<","<<j<<endl;
 k++;
    if(j==n+1) break;
 else{
  i=1; j=j-2; } }
    }


    if(k==0)cout<<"Not matched"<<endl;
if(k==1)cout<<k<<"time "<<endl;
    else if(k!=0)cout<<k<<"times"<<endl;
    cout<<endl;
}




int main(){
    int length1,length2;

    char pattern1[]=" aaab";
    char text1[]=" aaacaaab";
    length1=sizeof(pattern1)/ sizeof(pattern1[0])-2;
    length2= sizeof(text1)/ sizeof(text1[0])-2;
calc(pattern1,text1,length1,length2);

    char pattern2[]=" abacaa";
    char text2[]=" abacbabacaabcabacaa";
    length1=sizeof(pattern2)/ sizeof(pattern2[0])-2;
    length2=sizeof(text2)/ sizeof(text2[0])-2;
 calc(pattern2,text2,length1,length2);

    char pattern3[]=" abaababaabaab";
    char text3[]=" abaababaabacabaababaabaab";
    length1=sizeof(pattern3)/ sizeof(pattern3[0])-2;
    length2=sizeof(text3)/ sizeof(text3[0])-2;
    calc(pattern3,text3,length1,length2);

   char pattern4[]=" ilovebioinformatics";
    char text4[]=" iloveasportsverymuch";
    length1=sizeof(pattern4)/ sizeof(pattern4[0])-2;
    length2=sizeof(text4)/ sizeof(text4[0])-2;
    calc(pattern4,text4,length1,length2);

    char pattern5[]=" ilovebioinformatics";
    char text5[]=" istudyhardbecauseilovebioinformaticsverymuch";
    length1=sizeof(pattern5)/ sizeof(pattern5[0])-2;
    length2=sizeof(text5)/ sizeof(text5[0])-2;
    calc(pattern5,text5,length1,length2);


    char pattern6[]=" TTACTGAGCCACACAGGAAAACTTGCCTTATGATTTTGAAT";
    char text6[]=" TTTAAATCATACCAATTGAACCGAGCCTTGTAGAAACACTATCACCTACGCATACCTCTGCTTCTTTTCATTAACCTGCTATCCTCTTTACAAATGGGATTCTTCACCCACTCCCTTCTTCTAGATTAGCAATGCCCTGTTAAGTAAACGAACACGAAATTCAAAGGGAAACAGGAGCAATCATCATTACCAGCTGCCGTGTTAAGCATTGCGAAAACGCTCACGATTCACAGAAAAATCCATGCTGTTCTTTGAAGGCATTCAAGCCTTAATAGCTAGCTGGATGAATGTTTAACTTCTAGGCCAGGCACTACTCTGTCCCAACAATAAGCCCTGTACATTGGGAAAGGTGCCGAGACATGAACTTTGGTCTTCTCTGCAATCCATCTGGAGCATTCACTGACAACATCGACTTTGAAGTTGCACTGACCTGGCCAGCCCTGCCACTTACCAGGTTGGCTCTGTATGGCTAAGCGTTTTCTCCTAAAATCCCTTGAAAACTGTGAGAAGACCATAAGAAGATCATATCTTTAATTCTATTTCACAAGTCACACAATATTCCAATCAAATACAGATGGTTGAGAAAAGTCATCCATCTTCCCTCCCCACCCTCCCACAGCCCCTCAACCACTGCCCTGAAACTTATATGCTGTTATCCGCAGCTCCATCTGGAGCATCACAGCTACTGTCAACCCTGACGCTCTTTCTGAAAAAACACCGGATGGACATCAGAACTATTTCTTTAAGGATGTTACTGAGCCACACAGGAAAACTTGCCTTATGATTTTGAATGCACGGATCTGATTTGACTAAACATGATAACTAGAGAATCACCCAATCTACTCCCATTTTCAACTCTAAATCATCAGAGTGTCTCAAATCCAAAGCACACACAGACCAGCCTGGCCAACACGGTGAAACTCCACCCCTACTAAAAGTATAAAAATTATCCAGGTGTGGTGGCGGGCGCCTGTAATCCAAGCTACTTGGGAGTCTGGAGGCAGGAGAATCCCTTGAACCTGGGAGATGGAGGTTGCAGTGAGCAGAGATCACACCACCGCACTCTAGCCTGGGCCACAAATCAACAACAACAACAACAACAAAAAACAAAGCGCACACAGAGACTGAGGTCCTCTTTGGCATTGAGAAGATGGCTATGCAAGTCCCAACTAGCAAGTGCAAACTTCCCAGCTTCACTTCTGCCAGTGTCCCTTCACCCCTTCTCAACCCCACTGGGAGGCAGGAGGGTGCTTGACAATAACAGCCTTGGCATCACTCTGCCAGGGTGTAATAGGAACTGTTACAATTCTGAGATTCTGTGTAAGCACTGGCCTTTCTGCCTAGAATGCCTTCTCCTCTCTTTTTTAACTGCATGCTCCTATTTATCTTTCAAAGCCCGGAAAAAATAACACTGCACACGGGAAATGCTCCCTTCCTACTGCAGTCATTTAGATGACTCTATGCCATTCCATTCATTTCTCTTTCCTACCACAGAAGTGCTTTGAGATTTTGGAGTCAGACTGCTTGAACTTGAATCCTGGCCCTCTCATCAGAGACTTGACTTATTTTAGGCAAGTTATATAACCAATTTTACCTCAGTTCCTTACCCATAAAATGGGTCTAATGAGAGTACCTACCACACAGAATTTTGATGAAAACTGAATGAGATGAAGGCCTTTAAGGCAGTGGTCCCCAACCCTGGGGACACAGACAGGTACCATTTTGTGGCCTGTTAGGAACTGGGCCACACAGCAGGAGGTGAGCAGTGGGTGAGTGAGATCAGCGTTATTTACAGCTGCTCCCCATTGCTCACCTTACTGCCTGAGCTCCACCTCCTGTCAGATCAGCAGTGGCATTAAATTCTCATAGCAGCACAAACCCTGTCATGAACTGCACATGCGAGGGATCTAGGTTGTGCGCTCCTTATGAGAATCTAATGCCTAATGACCTGTCACCGTCTCCCATCACCCCTAGATGGGAGTGTCTAGTTGCAGGAAACAAGCTCAGGGCTTCCACTGATTCTACATTATGGTGAGTTGTATAATTATTTCATTATATAATACAATGTAATAATAATAGAAACACAGTGCACAACAAATGTAATGTGCTTGAATCATCCCCAAACCATCCCAGTCCACGGTCTTCCACATTTTGTCTTTTCACAAAATTGTCTTCCACAAAACTGGTCCCTGGTGCCAAAAAGGCTTGGGACCACTGCTTTAAAGCCTTTGCATAGTGCTTAGAATTGAGGGGGAAAAAAAAAACAAAAACAATGTAGCTAGTTGCTACAATCACTATATTGGTGAGTTTCAAAAGGAAAAGAATTCTGTCCCATTTATGCTTGAGCCTTGAGTTGCTAACCAAGCCTGACACAAAATTACTGTTGAAGGGATGTGTGAGTCCTAATTGAAATGAGGCCTCTTAAGGGAATTGTGGACCAAACCCCAAGCAGGCAGAAAGCCGTATCTTAATTATTGCAAGTATTTCAGGCAAGGTGTGGATGGCCATTTGAATTCAAGCAGACTAGGACCTGGGATGAGAAAGAAGGTGTGTACGTGACTTGATCTTTGAACTTTAGCTCACCATCTGGAAGAAGGCTGAGTATTCTCTGCACTCACATAGTAGCTAATGCCTACTCCCCAGCCACCCACAATTCTTTCTGTAGGAAGGCTCGCTAGAATACTTTGTGATATTGGATATTAGTTCCATATTCTACTGTGTATCTTAGTTCAACCAAATTGTAATCATCTGATATTTATTTCTTTTAATATAAATATAAGTATATTAAGTCTTGG";
    length1=sizeof(pattern6)/ sizeof(pattern6[0])-2;
    length2=sizeof(text6)/ sizeof(text6[0])-2;
    cout<<length1<<endl;
    cout<<length2;
    calc(pattern6,text6,length1,length2);

/*
    char pattern7[]=" ";
    char text7[]=" ";
    length1=sizeof(pattern7)/ sizeof(pattern7[0])-2;
    length2=sizeof(text7)/ sizeof(text7[0])-2;
    calc(pattern7,text7,length1,length2);
*/



}
